services:
  mongodb:
    image: mongo:8.3
    container_name: bsdynamodb-mongodb
    user: '1000:1000'
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: local
    volumes:
      - ./mongodb_data:/data/db
